apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: route
spec:
  grafana:
    enabled: false
    route: false
  prometheus:
    enabled: false
    route: false
  server:
    route: true
