apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudnativesampleapp-deployment
  labels:
    chart: cloudnativesampleapp-1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudnativesampleapp-selector
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: cloudnativesampleapp-selector
        version: current
    spec:
      containers:
      - name: cloudnativesampleapp
        image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9080
            name: http
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
        env:
        - name: PORT
          value: "9080"
        - name: APPLICATION_NAME
          value: cloudnativesampleapp
